### PR TITLE
Makefile cleanup. Add .gitignore.

### PR DESCRIPTION
**Pull request by jforissier**
- It is possible to override path to bl1.bin with $(BL1)
- Split targets l-loader.bin, ptable-linux.img, ptable-aosp.img

Signed-off-by: Jerome Forissier jerome.forissier@linaro.org

### CODE REVIEW

**Comment by jforissier** [comment]
Any feedback on this simple patch? I have rebased onto master.

**Comment by fboudra** [comment]
sorry for the long delay, it's in my queue to review. We've been busy by the upcoming release for Hikey.

**Comment by jforissier** [comment]
@fboudra np thanks :)

**Comment by jforissier** [comment]
BTW this is to be merged into the hikey branch, which is the base branch I've used, not master. I guess I've made a mistake by not selecting hikey when I created the PR.
What's the purpose of having two branches (hikey and master)? Should I rebase my patch on top of master instead?

**Comment by fboudra** [comment]
merged after being rebased on master:
https://github.com/96boards/l-loader/commit/ae29ee64a9c8ab4d59e8b999b2c079ef2a62cac8

**Pull request closed without merging**
